### ISSUE TITLE
数据集获取不了

### ISSUE THREAD

**Issue by JasonPeng1310** [shaido987/multi-dim-baselines#14]
这个数据集获取不了 All datasets are available at Tsinghua Cloud: https://cloud.tsinghua.edu.cn/d/aa4102a5d1614e57bc36/ 
可以提供一下网盘链接嘛

**Comment by shaido987** [comment]
Hello,

This should already be fixed by the first author of Squeeze, the new link is: https://zenodo.org/record/8153367
