### ISSUE TITLE
question of surprise in adtributor

### ISSUE THREAD

**Issue by davidlight2018** [shaido987/multi-dim-baselines#4]
The calculation of surprise value in adtributor seems not correct to me.

The JS divergense formula should be: 

![2021-12-15_18-19-49](https://user-images.githubusercontent.com/42494693/146168561-2bc97a5d-297a-4174-94f4-9e7f369e10a3.png)

So, the code should be: 

```python
p = df['predict'] / F
q = df['real'] / A
m = (p + q) / 2
df['surprise'] = 0.5 * np.sum(p * np.log(p/m)) + 0.5 * np.sum(q * np.log(q/m))
```

what do you think? thanks.

**Comment by shaido987** [comment]
This will give all leaf elements the same surprise independently of their usefulness so it would not be very useful (`df['surprise'] will have the same value for all rows). If you take a look at the original Adtributor paper[1], the surprise for an element is computed as:

![image](https://user-images.githubusercontent.com/1130029/146293312-24ec74f5-e19b-419e-a687-24c14c51e534.png)

For the code implementation, in `adtributor` the sum over leaf elements is done within the for loop to obtain the total surprise for an element, i.e. here:

```
for d in dimensions:
        elements = df.groupby(d).sum()
        elements = elements.sort_values('surprise', ascending=False)
        ...
```

For `adtributor_new` the sum is done at the beginning. There will therefore only be 1 element considered at the time and there is no need to sum (as it already has been done).

[1]: Bhagwan, Ranjita, et al., Adtributor: Revenue debugging in advertising systems." 11th USENIX Symposium on Networked Systems Design and Implementation (NSDI 14), 2014.

**Comment by davidlight2018** [comment]
thx, very helpful !

**Comment by shaido987** [comment]
No problems :)
